export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_PRODUCT = 'GET_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_CART = 'GET_CART'
